# Introduction to Pandas
1. Series - Series Object is one dimensional
2. Data Frame -  Two dimensional data

In [1]:
# Series Object is one dimensional
import pandas as pd

data = [1, 2, 3, 4]
series = pd.Series(data)

print(series)

print(type(series))

0    1
1    2
2    3
3    4
dtype: int64
<class 'pandas.Series'>

In [4]:
# changing the index

import pandas as pd

data = [1, 2, 3, 4]
series = pd.Series(data, index=['a', 'b', 'c', 'd'])

print(series)

print(type(series))

a    1
b    2
c    3
d    4
dtype: int64
<class 'pandas.Series'>

# Features Data Frame

1. Two Dimensional Data
2. Different Column Types
3. Mutable Size
4. Arithmatic Operations on rows and column
5. Labeled axis

In [10]:
data = [1, 2, 3, 4, 5]
df = pd.DataFrame(data)

print('Creating DataFrame using List:', df, '\n\n')

Creating DataFrame using List:    0
0  1
1  2
2  3
3  4
4  5

In [12]:
dict = {'fruits': ['apple', 'banana', 'mango'], 'count': [10, 20, 30]}
df = pd.DataFrame(dict)

print('Creating DataFrame using Dictionary:', df, '\n\n')

Creating DataFrame using Dictionary:    fruits  count
0   apple     10
1  banana     20
2   mango     30

In [13]:
# creating a data frame using series

data = [1, 2, 3, 4]
series = pd.Series(data, index=['a', 'b', 'c', 'd'])

df = pd.DataFrame(series)

print('Creating DataFrame using Series:', df, '\n\n')

Creating DataFrame using Series:    0
a  1
b  2
c  3
d  4

In [1]:
# creating a data frame using numpy array
import numpy as np
import pandas as pd

data = np.array([[10000, 20000, 30000], ['A', 'B', 'C']])

df = pd.DataFrame({
    'name': data[1],
    'salary': data[0],
})

print('Creating DataFrame using Numpy Array: \n', df, '\n\n')

Creating DataFrame using Numpy Array:
   name salary
0    A  10000
1    B  20000
2    C  30000

In [5]:
# Merge between two data frame

players = ['p1', 'p2', 'p3']
points = [8, 10, 12]
games = ['g1', 'g2', 'g3']

df1 = pd.DataFrame({
    'Players': players,
    'Points': points,
    'Games': games,
})
df1

  Players  Points Games
0      p1       8    g1
1      p2      10    g2
2      p3      12    g3

In [7]:
# Merge between two data frame

players = ['p1', 'p5', 'p6']
powers = ['sprint', 'jump', 'lick']
games = ['g1', 'g2', 'g3']

df2 = pd.DataFrame({
    'Players': players,
    'Powers': powers,
    'Games': games,
})
df2

  Players  Powers Games
0      p1  sprint    g1
1      p5    jump    g2
2      p6    lick    g3

In [8]:
# now merge df1 and df2 using INNER MERGE (DEFAULT) based on any common column

df1.merge(df2, on='Players', how='inner')

  Players  Points Games_x  Powers Games_y
0      p1       8      g1  sprint      g1

In [9]:
# now merge df1 and df2 using LEFT MERGE based on any common column

df1.merge(df2, on='Players', how='left')

  Players  Points Games_x  Powers Games_y
0      p1       8      g1  sprint      g1
1      p2      10      g2     NaN     NaN
2      p3      12      g3     NaN     NaN

In [10]:
# now merge df1 and df2 using RIGHT MERGE based on any common column

df1.merge(df2, on='Players', how='right')

  Players  Points Games_x  Powers Games_y
0      p1     8.0      g1  sprint      g1
1      p5     NaN     NaN    jump      g2
2      p6     NaN     NaN    lick      g3

# Join using panda

## merge - atleast 1 common column between two datasets
## join - atleast 1 common index between two datasets

In [23]:
# Merge between two data frame

players = ['p1', 'p5', 'p6']
powers = ['sprint', 'jump', 'lick']
games = ['g1', 'g2', 'g3']

df3 = pd.DataFrame({
    'Playerss': players,
    'Powerss': powers,
    'Gamess': games,
}, index=['L1', 'L2', 'L3'])
df3

players = ['p1', 'p3', 'p4']
powers = ['sprint', 'jump', 'lick']
games = ['g1', 'g2', 'g3']

df4 = pd.DataFrame({
    'Players': players,
    'Powers': powers,
    'Games': games,
}, index=['L1', 'L2', 'L3'])
df4

   Players  Powers Games
L1      p1  sprint    g1
L2      p3    jump    g2
L3      p4    lick    g3

In [24]:
df3.join(df4, how='inner')

   Playerss Powerss Gamess Players  Powers Games
L1       p1  sprint     g1      p1  sprint    g1
L2       p5    jump     g2      p3    jump    g2
L3       p6    lick     g3      p4    lick    g3

In [25]:
# Left Join

df3.join(df4, how='left')

   Playerss Powerss Gamess Players  Powers Games
L1       p1  sprint     g1      p1  sprint    g1
L2       p5    jump     g2      p3    jump    g2
L3       p6    lick     g3      p4    lick    g3

In [26]:
# Left Join

df3.join(df4, how='right')

   Playerss Powerss Gamess Players  Powers Games
L1       p1  sprint     g1      p1  sprint    g1
L2       p5    jump     g2      p3    jump    g2
L3       p6    lick     g3      p4    lick    g3

# Concatenate

pd.concat(df3, df4)

In [31]:
import pandas as pd
pd.concat([df3, df4])

   Playerss Powerss Gamess Players  Powers Games
L1       p1  sprint     g1     NaN     NaN   NaN
L2       p5    jump     g2     NaN     NaN   NaN
L3       p6    lick     g3     NaN     NaN   NaN
L1      NaN     NaN    NaN      p1  sprint    g1
L2      NaN     NaN    NaN      p3    jump    g2
L3      NaN     NaN    NaN      p4    lick    g3

# Import dataset using pandas

# Analyzing dataset using pandas

In [53]:
import pandas as pd

cars = pd.read_csv('./datasets/cars.csv')

cars

# type(cars) # pandas.DataFrame

# cars.head(15)

# cars.tail(15)

# cars.shape

# cars.info()

# cars.mean()
# cars.mode()
# cars.median()

# cars.count()

# cars.describe()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

# Cleaning Dataset
1. Renaming columns

In [58]:
# renaming column

# dataset.rename(columns={'Unnamed: 1': model})

cars.rename(columns={'model: 1': 'models'})

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [60]:
# Replace all null values with mean on qsec

cars.qsec = cars.qsec.fillna(cars.qsec.mean)
cars

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

# Drop unwanted columns

## cars.drop(columns=['S.No.'])

# Change Column type

## df.column_name.astype(new datatype)

### cars.disp.astype(float64)

# Correlation

## cars['col1', 'col2'].corr()

# Indexing on dataset

1. I want to see only hp column in cars dataset
2. I want to see first 5 records from hp column in cars dataset
3. List all records of mpg column
4. list all records of mpg to qsec column
5. setting entire column value

In [68]:
# 1. I want to see only hp column in cars dataset

cars.iloc[:, 4]

0     110
1     110
2      93
3     110
4     175
5     105
6     245
7      62
8      95
9     123
10    123
11    180
12    180
13    180
14    205
15    215
16    230
17     66
18     52
19     65
20     97
21    150
22    150
23    245
24    175
25     66
26     91
27    113
28    264
29    175
30    335
31    109
Name: hp, dtype: int64

In [69]:
# 2. I want to see first 5 records from hp column in cars dataset

cars.iloc[:5, 4]

0    110
1    110
2     93
3    110
4    175
Name: hp, dtype: int64

In [71]:
# 3. list all records of mpg column

cars.loc[:, 'mpg']

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [74]:
# 4. list all records of mpg to qsec column

cars.loc[:6, 'mpg':'qsec']

    mpg  cyl   disp   hp  drat     wt   qsec
0  21.0    6  160.0  110  3.90  2.620  16.46
1  21.0    6  160.0  110  3.90  2.875  17.02
2  22.8    4  108.0   93  3.85  2.320  18.61
3  21.4    6  258.0  110  3.08  3.215  19.44
4  18.7    8  360.0  175  3.15  3.440  17.02
5  18.1    6  225.0  105  2.76  3.460  20.22
6  14.3    8  360.0  245  3.21  3.570  15.84

In [90]:
# 5. setting entire column value 

cars['am'] = 1
cars

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
31,Volvo 142E,21.4,False,121.0,109,4.11,2.780,18.60,1,1,4,2
5,Valiant,18.1,False,225.0,105,2.76,3.460,20.22,1,1,3,1
20,Toyota Corona,21.5,False,120.1,97,3.70,2.465,20.01,1,1,3,1
19,Toyota Corolla,33.9,False,71.1,65,4.22,1.835,19.90,1,1,4,1
26,Porsche 914-2,26.0,False,120.3,91,4.43,2.140,16.70,0,1,5,2
24,Pontiac Firebird,19.2,True,400.0,175,3.08,3.845,17.05,0,1,3,2
13,Merc 450SLC,15.2,True,275.8,180,3.07,3.780,18.00,0,1,3,3
12,Merc 450SL,17.3,True,275.8,180,3.07,3.730,17.60,0,1,3,3
11,Merc 450SE,16.4,True,275.8,180,3.07,4.070,17.40,0,1,3,3
10,Merc 280C,17.8,False,167.6,123,3.92,3.440,18.90,1,1,4,4
9,Merc 280,19.2,False,167.6,123,3.92,3.440,18.30,1,1,4,4
7,Merc 240D,24.4,False,146.7,62,3.69,3.190,20.00,1,1,4,2
8,Merc 230,22.8,False,140.8,95,3.92,3.150,22.90,1,1,4,2
1,Mazda RX4 Wag,21.0,False,160.0,110,3.90,2.875,17.02,0,1,4,4
0,Mazda RX4,21.0,False,160.0,110,3.90,2.620,16.46,0,1,4,4
30,Maserati Bora,15.0,True,301.0,335,3.54,3.570,14.60,0,1,5,8
27,Lotus Europa,30.4,False,95.1,113,3.77,1.513,16.90,1,1,5,2
15,Lincoln Continental,10.4,True,460.0,215,3.00,5.424,17.82,0,1,3,4
4,Hornet Sportabout,18.7,True,360.0,175,3.15,3.440,17.02,0,1,3,2
3,Hornet 4 Drive,21.4,False,258.0,110,3.08,3.215,19.44,1,1,3,1
18,Honda Civic,30.4,False,75.7,52,4.93,1.615,18.52,1,1,4,2
28,Ford Pantera L,15.8,True,351.0,264,4.22,3.170,14.50,0,1,5,4
25,Fiat X1-9,27.3,False,79.0,66,4.08,1.935,18.90,1,1,4,1
17,Fiat 128,32.4,False,78.7,66,4.08,2.200,19.47,1,1,4,1
29,Ferrari Dino,19.7,False,145.0,175,3.62,2.770,15.50,0,1,5,6
6,Duster 360,14.3,True,360.0,245,3.21,3.570,15.84,0,1,3,4
21,Dodge Challenger,15.5,True,318.0,150,2.76,3.520,16.87,0,1,3,2
2,Datsun 710,22.8,False,108.0,93,3.85,2.320,18.61,1,1,4,1
16,Chrysler Imperial,14.7,True,440.0,230,3.23,5.345,17.42,0,1,3,4
23,Camaro Z28,13.3,True,350.0,245,3.73,3.840,15.41,0,1,3,4
14,Cadillac Fleetwood,10.4,True,472.0,205,2.93,5.250,17.98,0,1,3,4
22,AMC Javelin,15.2,True,304.0,150,3.15,3.435,17.30,0,1,3,2

# Lamda Function

In [79]:
f = lambda x: x*2

cars['am'] = cars['am'].apply(f)

cars

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,12,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,12,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,12,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,12,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,12,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,12,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,12,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,12,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,12,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,12,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,12,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,12,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,12,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,12,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,12,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,12,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,12,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,12,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,12,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,12,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,12,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,12,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,12,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,12,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,12,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,12,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,12,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,12,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,12,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,12,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,12,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,12,4,2

# Sorting

In [89]:
cars = cars.sort_values(by='model', ascending=False)
cars

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
31,Volvo 142E,21.4,False,121.0,109,4.11,2.780,18.60,1,12,4,2
5,Valiant,18.1,False,225.0,105,2.76,3.460,20.22,1,12,3,1
20,Toyota Corona,21.5,False,120.1,97,3.70,2.465,20.01,1,12,3,1
19,Toyota Corolla,33.9,False,71.1,65,4.22,1.835,19.90,1,12,4,1
26,Porsche 914-2,26.0,False,120.3,91,4.43,2.140,16.70,0,12,5,2
24,Pontiac Firebird,19.2,True,400.0,175,3.08,3.845,17.05,0,12,3,2
13,Merc 450SLC,15.2,True,275.8,180,3.07,3.780,18.00,0,12,3,3
12,Merc 450SL,17.3,True,275.8,180,3.07,3.730,17.60,0,12,3,3
11,Merc 450SE,16.4,True,275.8,180,3.07,4.070,17.40,0,12,3,3
10,Merc 280C,17.8,False,167.6,123,3.92,3.440,18.90,1,12,4,4
9,Merc 280,19.2,False,167.6,123,3.92,3.440,18.30,1,12,4,4
7,Merc 240D,24.4,False,146.7,62,3.69,3.190,20.00,1,12,4,2
8,Merc 230,22.8,False,140.8,95,3.92,3.150,22.90,1,12,4,2
1,Mazda RX4 Wag,21.0,False,160.0,110,3.90,2.875,17.02,0,12,4,4
0,Mazda RX4,21.0,False,160.0,110,3.90,2.620,16.46,0,12,4,4
30,Maserati Bora,15.0,True,301.0,335,3.54,3.570,14.60,0,12,5,8
27,Lotus Europa,30.4,False,95.1,113,3.77,1.513,16.90,1,12,5,2
15,Lincoln Continental,10.4,True,460.0,215,3.00,5.424,17.82,0,12,3,4
4,Hornet Sportabout,18.7,True,360.0,175,3.15,3.440,17.02,0,12,3,2
3,Hornet 4 Drive,21.4,False,258.0,110,3.08,3.215,19.44,1,12,3,1
18,Honda Civic,30.4,False,75.7,52,4.93,1.615,18.52,1,12,4,2
28,Ford Pantera L,15.8,True,351.0,264,4.22,3.170,14.50,0,12,5,4
25,Fiat X1-9,27.3,False,79.0,66,4.08,1.935,18.90,1,12,4,1
17,Fiat 128,32.4,False,78.7,66,4.08,2.200,19.47,1,12,4,1
29,Ferrari Dino,19.7,False,145.0,175,3.62,2.770,15.50,0,12,5,6
6,Duster 360,14.3,True,360.0,245,3.21,3.570,15.84,0,12,3,4
21,Dodge Challenger,15.5,True,318.0,150,2.76,3.520,16.87,0,12,3,2
2,Datsun 710,22.8,False,108.0,93,3.85,2.320,18.61,1,12,4,1
16,Chrysler Imperial,14.7,True,440.0,230,3.23,5.345,17.42,0,12,3,4
23,Camaro Z28,13.3,True,350.0,245,3.73,3.840,15.41,0,12,3,4
14,Cadillac Fleetwood,10.4,True,472.0,205,2.93,5.250,17.98,0,12,3,4
22,AMC Javelin,15.2,True,304.0,150,3.15,3.435,17.30,0,12,3,2

# Filtering

In [2]:
x = cars['cyl'] > 6
y = cars[x]
y

NameError: name 'cars' is not defined